In [1]:
import numpy as np

list = [1,2,3,4,5]
print(list)
arr = np.array(list)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [6]:
# 문자열과 숫자가 혼합된 리스트 --> 문자열형으로 통일
arr = np.array([1, 'a', 3])
print(arr)

['1' 'a' '3']


In [4]:
# 정수와 실수가 혼합된 리스트 --> 실수형으로 통일
arr = np.array([1, 2, 0.3])
print(arr)

[1.  2.  0.3]


List와 같은 방볍으로 arr의 인덱싱과 슬라이싱 가능

In [8]:
arr = np.array([1, 2, 3, 4, 5])
arr[2]
arr[-3]

3

In [14]:
arr = np.array([2, 6, 8 ,9, 12, 23, 27, 32, 35])
# arr[0:8:2]
# arr[::2]
# arr[-1:]
# arr[:-1]
arr[:3]

array([2, 6, 8])

1차원과 2차원 arr의 shape 알아보기

In [22]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

arr2 = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(arr2)

print(arr1,shape)
print(arr2,shape)

ModuleNotFoundError: ignored

random 함수로 만들기

In [20]:
import random

np.random.random((2, 3))

array([[0.13016452, 0.93496506, 0.74342084],
       [0.34173439, 0.13295334, 0.26473443]])

In [19]:
np.random.randint(0, 10, size=(2,3))

array([[1, 8, 2],
       [7, 5, 9]])

특정 범위의 숫자를 배열로 생성하기 np.arange(start, end, step)

In [24]:
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np.arange(1, 2, 0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Numpy 배열 간의 기본연산 해보기

In [28]:
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([5,10,15,20,25])
result = arr1 + arr2
print(result)

[ 7 14 21 28 35]


함수 where()을 활용한 필터링

In [29]:
arr = np.array([38,16,1,27,55,8,19])
print(np.where(arr>20))

(array([0, 3, 4]),)


sort 함수는 배열을 정렬하는 데 사용

In [50]:
arr = [8, 16, 1, 55, 27, 28]
np.sort(arr)[::-1]

array([55, 28, 27, 16,  8,  1])

마무리 문제

In [73]:
coffee = [87, 63, 64, 110, 144, 143, 69, 53, 133, 55, 78, 123, 63, 101]
c = []
waffle = [87, 36, 32, 101, 41, 78, 115, 31, 53, 11, 13, 119, 25 ,65]
w = []

coffee = np.array(coffee ) * 3400
waffle = np.array(waffle) * 6700

cfe1 = np.sum(coffee)
cfe2 = int(np.sum(coffee)/14)
wfl1 = np.sum(waffle)
wfl2 = int(np.sum(waffle)/14)

total = coffee + waffle

day_total = np.where(total <= 450000)
result = total[day_total]


print(f'커피의 일별 매출 : {coffee}')
print(f'와플의 일별 매출 : {waffle}')

print(f'커피의 총 매출 : {cfe1}')
print(f'커피의 평균 매출 : {cfe2}')
print(f'와플의 총 매출 : {wfl1}')
print(f'와플의 평균 매출 : {wfl2}')

print(f'일별 총 매출 {total}')

print(f'450000원 넘은 날은 : {day_total}')
print(f'안 넘은 날 매출 : {result}')

커피의 일별 매출 : [295800 214200 217600 374000 489600 486200 234600 180200 452200 187000
 265200 418200 214200 343400]
와플의 일별 매출 : [582900 241200 214400 676700 274700 522600 770500 207700 355100  73700
  87100 797300 167500 435500]
커피의 총 매출 : 4372400
커피의 평균 매출 : 312314
와플의 총 매출 : 5406900
와플의 평균 매출 : 386207
일별 총 매출 [ 878700  455400  432000 1050700  764300 1008800 1005100  387900  807300
  260700  352300 1215500  381700  778900]
450000원 넘은 날은 : (array([ 2,  7,  9, 10, 12]),)
넘은 날 매출 : [432000 387900 260700 352300 381700]
